### ISSUE TITLE
Highlights are yellow with white font

### ISSUE THREAD

**Issue by kameit00** [vandermerwed/Roam-Research-Dark#10]
If I highlight text `^^highlighted text^^`, the text is yellow with white characters. That is very hard to read.

I looked into the original CSS and found:
```css
.roam-highlight {
    background-color: #fef09f;
    margin: -2px;
    padding: 2px;
}
```

I added 
```css
.roam-highlight {
    background-color: #795548;
    background-color: rgba(121, 85, 72, .60);
}
```
Copied from your `.block-highlight-yellow`. This works for me now.
But I think it will be overriden if there is an update of your Style.

It would be nice if you could look into the `.roam-highlight`.

Thanks
Kai
